language: generic
sudo: required
services: 
    - docker
    
before_install: 
    - docker build -t mcreach/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true mcreach/react-test npm run test -- --coverage
    
after_success:
    - docker build -t mcreach/multi-client -f ./client/Dockerfile ./client
    - docker build -t mcreach/multi-server -f ./server/Dockerfile ./server
    - docker build -t mcreach/multi-nginx  -f ./nginx/Dockerfile  ./nginx
    - docker build -t mcreach/multi-worker -f ./worker/Dockerfile ./worker
    
    #Logging Docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    # --> Non sécurisé, password stocké de façon non crypté dans  /home/travis/.docker/config.json.
    
    #Envoyer les différentes images générer pour la poduction vers Dockerhub
    - docker push mcreach/multi-client
    - docker push mcreach/multi-server
    - docker push mcreach/multi-nginx
    - docker push mcreach/multi-worker
    
    #AWS Deployment
    
deploy:
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-231556070134
    bucket_path: multi-docker
    on:
        branch: master
        
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

    